# Actuator
management.endpoints.web.exposure.include: "*"

ApiVersion: 1
AuthClientId: "942178444843-7aun6j3qv9dtaq7uqdbth0lvhaiumfqq.apps.googleusercontent.com"

spring.jpa:
  open-in-view: false
  generate-ddl: true
  properties:
    javax:
      persistence:
        schema-generation:
          database:
            action: update
    hibernate:
      show_sql: true
      use_sql_comments: true
      format_sql: true
      generate_statistics: false
      jdbc:
        fetch_size: 2000
        lob.non_contextual_creation: true
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: update
      hbm2dll:
        create_namespaces: true

spring.datasource:
  url: "jdbc:h2:mem:vendingdb"
  username: "sa"
  password: "vhhs"

---
spring:
  profiles: mysql

# Actuator
management.endpoints.web.exposure.include: "*"

ApiVersion: 1
AuthClientId: "942178444843-7aun6j3qv9dtaq7uqdbth0lvhaiumfqq.apps.googleusercontent.com"

spring.jpa:
  open-in-view: false
  generate-ddl: true
  properties:
    javax:
      persistence:
        schema-generation:
          database:
            action: update
    hibernate:
      show_sql: true
      use_sql_comments: true
      format_sql: true
      generate_statistics: false
      jdbc:
        fetch_size: 2000
        lob.non_contextual_creation: true
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: update
      hbm2dll:
        create_namespaces: true

spring.datasource:
  url: ${MYSQL_URL:jdbc:mysql://localhost/vendingdb}
  username: ${MYSQL_USER:vending}
  password: ${MYSQL_PASS:VHHSdemo@128}
